name: OpenWrt for Mediatek_mt7988a_bpi-r4 and release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: Baronshaw/immortalwrt
  REMOTE_BRANCH: v24.10.0-r1
  CONFIG_FILE: bpi-r4.config
  RELEASE_PREFIX: Mediatek_mt7988a_bpi-r4

jobs:  
  build:
    name: Build OpenWrt
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
                              g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
                              libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
                              libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
                              ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
                              python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
                              upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "current_repo"

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Configure firmware image
        run: |
          mv current_repo/${{ env.CONFIG_FILE }} .config
          make defconfig
      - name: Try to fetch dependencies cache
        uses: actions/cache/restore@v4
        with:
          path: dl
          key: dl-${{ runner.os }}-${{ github.run_id }}
          restore-keys: dl-${{ runner.os }}

      - name: Download dependencies
        run: make -j$(($(nproc)+1)) download

      - name: Update dependencies cache every run
        uses: actions/cache/save@v4
        with:
          path: dl
          key: dl-${{ runner.os }}-${{ github.run_id }}

      - name: Try to fetch host packages and toolchain cache
        uses: actions/cache/restore@v4
        with:
          path: |
            staging_dir/host
            staging_dir/hostpkg
            staging_dir/toolchain-aarch64_cortex-a53_gcc-14.2.0_musl
          key: toolchain-${{ runner.os }}-${{ github.run_id }}
          restore-keys: toolchain-${{ runner.os }}

      - name: Build the firmware image
        run: make -j1

      - name: Update host packages and toolchain cache
        uses: actions/cache/save@v4
        with:
          path: |
            staging_dir/host
            staging_dir/hostpkg
            staging_dir/toolchain-aarch64_cortex-a53_gcc-14.2.0_musl
          key: toolchain-${{ runner.os }}-${{ github.run_id }}
      
      - name: Package output
        run: tar -cvf bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

  release:
    name: Create release
    needs: [build]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images
      
      - name: Extract artifacts
        run: tar xf bpi_r4-images.tar
      
      - name: Get current date
        run: |
          echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV
          echo -n "BUILD_VER_STR=$( cat bin/targets/mediatek/filogic/profiles.json | jq -r '.profiles.[].image_prefix' | sed -E 's/openwrt-(v24-snapshot-.*?-r[0-9]{2,3})-mediatek-filogic-bananapi_bpi-r4/\1/' )" >> $GITHUB_ENV
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.BUILD_VER_STR }}
          name: Openwrt BPI-r4 ${{ env.BUILD_VER_STR }}
          body: |
            Uploaded on: ${{ env.RELEASE_DATE }}
            Build Commit: ${{ needs.check_commits.outputs.latest_commit_sha }}
      
      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
